### ISSUE TITLE
cross-site errors in local instance

### ISSUE THREAD

**Issue by arebe** [priyankasuresh/cold_storage#2]
Assets should be in their own dirs for logical organization of the site data. However, JSON files (coldstorage.json) must be in the root dir for Chrome to find them, even if using an HTTP server like python SimpleHTTPServer. 

A potential work-around is to use the d3 JSON object instead of jQuery's $.getJSON(). But this really shouldn't be. Unclear if this would be an issue on a live webserver (presumably not, but the current live website has all of the JSON files in root).

**Comment by arebe** [comment]
running MAMP locally seems to have resolved the problem. not sure why MAMP works but python SimpleHTTPServer does not...but it seems to work in Chrome now :)

**Comment by izzoilgaM** [comment]
Aha! Glad to hear. I got tied up in a photo shoot at the Harvard Poetry Room and promoting our Experimental Teaching workshop today, but should have most of the day tomorrow on Cold Storage. 

—
Sent by a roaming carrier pigeon
